In [1]:
import numpy as np 
import pandas as pd

# Creating a DataFrame

In [4]:
data = {'Name':['John','Anna','Peter','Linda'],
         'Age':[28,34,29,42],
         'City':['New York','Paris','Berlin','London'],
         'Salary':[65000,70000,62000,85000] 
       }
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
data_list = [
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000], 
    ['Linda',42,'London',85000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Selection and Indexing of Columns

In [14]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [16]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [17]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

# Creating a new Column

In [18]:
df2['Designation'] = ['Doctor','Engineer','Doctor','Engineer']

In [19]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

# Removing Colums

In [23]:
df2.drop('Designation',axis=1,inplace=True)

In [24]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
df2.drop('City',axis=1)

    Name  Age  Salary
0   John   28   65000
1   Anna   34   70000
2  Peter   29   62000
3  Linda   42   85000

In [26]:
df2.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [27]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Selecting rows

In [28]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [31]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [32]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

# Selecting subsets of Rows and Columns

In [33]:
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [34]:
df2.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

# Conditional Selection

In [35]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [37]:
# I only want to see whose age is above 30

In [38]:
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [39]:
# I only want people whose age is above 30 and their city must be paris

In [43]:
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000